# Generated by Django 6.0.6 on 2026-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('peso_rolo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_rolo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
