# Generated by Django 6.0.6 on 2026-06-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia_watts', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_equipamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vida_util_horas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
