# Generated by Django 6.0.6 on 2026-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impressora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('custo_mao_obra_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margem_lucro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
