# Generated by Django 6.0.6 on 2026-06-27 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaocusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_peca', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tempo_impressao_horas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField(default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.impressora')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
    ]
