# Generated by Django 6.0.6 on 2026-07-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='vida_util_horas',
            field=models.PositiveIntegerField(),
        ),
    ]
