# Generated by Django 6.0.6 on 2026-07-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_impressora_ativa_alter_impressora_vida_util_horas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='valor_rolo',
            new_name='valor',
        ),
    ]
