# Generated by Django 6.0.6 on 2026-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_valor_rolo_material_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='impressoras/'),
        ),
    ]
