# Generated by Django 6.0.6 on 2026-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_impressora_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='nome_peca',
            field=models.CharField(default='Peça sem nome', max_length=150, verbose_name='Nome da peça'),
            preserve_default=False,
        ),
    ]
