# Generated by Django 6.0.6 on 2026-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orcamento_nome_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
