# Generated by Django 6.0.6 on 2026-07-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orcamento_cliente_orcamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('producao', 'Em produção'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='novo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='impressora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.impressora', verbose_name='Impressora'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
