# Generated by Django 6.0.6 on 2026-07-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orcamento_status_alter_orcamento_impressora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_criacao']},
        ),
    ]
