# Generated by Django 6.0.6 on 2026-07-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orcamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tempo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Tempo de preparação (horas)'),
        ),
    ]
