# Generated by Django 6.0.6 on 2026-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orcamento_tempo_mao_obra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaocusto',
            options={'verbose_name': 'Configuração de custo', 'verbose_name_plural': 'Configurações de custo'},
        ),
        migrations.AlterModelOptions(
            name='impressora',
            options={'verbose_name': 'Impressora', 'verbose_name_plural': 'Impressoras'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_mao_obra_hora_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo da mão de obra utilizado'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='margem_lucro_utilizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margem de lucro utilizada'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_kwh_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do kWh utilizado'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_material_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do material utilizado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_rolo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso do rolo (g)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tempo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Tempo de mão de obra (horas)'),
        ),
    ]
