# Generated by Django 6.0.6 on 2026-08-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_configuracaocusto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocusto',
            name='custo_mao_obra_acabamento_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Custo da mão de obra de acabamento (R$/hora)'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_mao_obra_acabamento_hora_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo da mão de obra de acabamento utilizado'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tempo_acabamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tempo de acabamento (horas)'),
        ),
    ]
